- name: Root
  hosts: localhost
  tasks:

- import_playbook:  platform/debian/playbook.yml
  when: ansible_facts['os_family'] == "Debian"  

- import_playbook:  platform/darwin/playbook.yml
  when: ansible_facts['os_family'] == "Darwin"

- import_playbook: platform/general/playbook.yml