---
- name: Debian
  hosts: localhost
  tasks:
  - name: Install apt packages
    become: true
    apt: 
      pkg:
        - zsh
        - tmux
        - tmuxinator
        - htop
        - openjdk-11-jdk
        - jq
        - moreutils # this is where sponge lives

  - name: Check if sdkman is installed 
    shell: test -d ~/.sdkman && echo "yes" || echo "no"
    register: is_sdkman_installed

  - name: Install SDKMan Package Manager
    shell: curl -s http://get.sdkman.io | bash executable=/bin/bash
    when : is_sdkman_installed.stdout == "no"
    
  - name: Copy source scripts
    copy:
      src: ./source
      dest: ~/.zsh_scripts/debian
      mode: '+x'
    
  - name: Copy path scripts
    copy:
      src: ./path
      dest: ~/.zsh_scripts/debian
      mode: '+x'