---
- name: General
  hosts: localhost
  tasks:
    - name: Create scripts folder
      file:
        state: directory
        path: ~/.zsh_scripts
        mode: '+x'
    
    - name: Copy source scripts
      copy:
        src: ./source
        dest: ~/.zsh_scripts
        mode: '+x'
    
    - name: Copy path scripts
      copy:
        src: ./path
        dest: ~/.zsh_scripts
        mode: '+x'
    
    - name: Append to zshrc
      blockinfile: path=~/.zshrc block={{lookup('file', './fragments/zshrc-fragment')}} create=yes state=present

    - name: Create .tmuxinator folder
      file:
        state: directory
        path: ~/.tmuxinator
        mode: '+x'

    - name: copy tmuxinator projects
      copy:
        src: .tmuxinator
        dest: ~/
        mode: '+x'