---
- name: General
  hosts: localhost
  tasks:
    - name: Copy source scripts
      copy:
        src: ./source
        dest: ~/.zsh_scripts
        mode: '+x'
    
    - name: Copy path scripts
      copy:
        src: ./path
        dest: ~/.zsh_scripts
        mode: '+x'

    - name: copy tmuxinator projects
      copy:
        src: .tmuxinator
        dest: ~/
        mode: '+x'

    - name: create context.json
      file:
        path: ~/.zsh_scripts/context.json
        state: touch
        mode: 'u=rw,g=r,o=r'
        modification_time: preserve
        access_time: preserve

    - name: copy context.json
      copy:
        src: ./context.json
        dest: ~/.zsh_scripts/context.json
        mode: '0644'

    - name: Append to zshrc
      blockinfile: path=~/.zshrc block={{lookup('file', './fragments/zshrc-fragment')}} create=yes state=present
